GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes/ HTTP/1.1
Content-Type: application/json

{
    "content": "Testing HTTP POST via VS Code REST client",
    "important": true
}

###
DELETE http://localhost:3001/api/notes/63b3aca3cc6dabd6b83a9db5 HTTP/1.1